In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
data = pd.read_csv("Social_Network_Ads.csv")

In [ ]:
data.head()

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
data.describe()

              Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB

In [ ]:
data.Purchased.value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [ ]:
# Rules for Classification using ANN
# ==============================================
# 1. Data must be complete
# 2. Data must be strictly numeric
# 3. Features and label must be in the form of 2d np array
# 4. Scaling of features is OPTIONAL (But Prashant Nair apply the same rules of Scaling as in Regression)
# 5. For Label (MANDATORY)
#        a. Binary Classification: Label must be represented in the form of 0 or 1
#        b. Multiclass Classification: Label must be either DISCRETE NUMERICAL or DUMMY VARIABLE

In [ ]:
#Seperate data as features and label
features = data.iloc[:,[0,1]].values
label = data.iloc[:,[2]].values

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
features = sc.fit_transform(features)

In [ ]:
#Label Normalization
# Here data is by default 0 and 1 , so no changes/preprocessing required

In [ ]:
#Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(features,
                                                 label,
                                                 test_size=0.2,
                                                 random_state=10)

#ANN Modelling

# Changing Optimizer Algo

In [ ]:
#Architect the model
import tensorflow as tf

model = tf.keras.Sequential()

model.add(tf.keras.layers.Dense(units = 6 , activation="relu", input_shape=(2,)))
model.add(tf.keras.layers.Dense(units = 6 , activation="relu"))
model.add(tf.keras.layers.Dense(units = 1 , activation="sigmoid"))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
#Compile Model

#For Classification
# Loss Function:
# a. Binary Classification: binary_crossentropy
# b. Multi-class Classification: categorical_crossentropy | sparse_categorical_crossentropy


model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [ ]:
class MyCLRuleMonitor(tf.keras.callbacks.Callback):
  def __init__(self,cl):
    super(MyCLRuleMonitor,self).__init__()
    self.cl=cl

  def on_epoch_end(self,epoch,logs=None):
    testScore = logs['val_accuracy']
    trainScore = logs['accuracy']

    if testScore > trainScore and testScore >= self.cl:
      self.model.stop_training=True

In [ ]:
model.fit(X_train,y_train, validation_data=(X_test,y_test), epochs=10000, callbacks=[MyCLRuleMonitor(0.9)])

Epoch 1/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 3s 91ms/step - accuracy: 0.3741 - loss: 0.6960 - val_accuracy: 0.3625 - val_loss: 0.6727
Epoch 2/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.3896 - loss: 0.6808 - val_accuracy: 0.4375 - val_loss: 0.6615
Epoch 3/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4889 - loss: 0.6731 - val_accuracy: 0.4875 - val_loss: 0.6511
Epoch 4/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5391 - loss: 0.6670 - val_accuracy: 0.5375 - val_loss: 0.6416
Epoch 5/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5698 - loss: 0.6513 - val_accuracy: 0.6000 - val_loss: 0.6331
Epoch 6/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6200 - loss: 0.6556 - val_accuracy: 0.6250 - val_loss: 0.6254
Epoch 7/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6296 - loss: 0.6405 - val_accuracy: 0.6750 - val_loss: 0.6183
Epoch 8/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6625 - loss: 0.6349 - val_accuracy: 0.6750 - val_loss: 0.6118
Epoch 9/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7175 - loss: 0.6320 - val_accuracy: 0.7125 - val_loss: 0.6056
Epoch 10/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7194 - loss: 0.6177 - val_accuracy: 0.7375 - val_loss: 0.5999
Epoch 11/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7043 - loss: 0.6217 - val_accuracy: 0.7375 - val_loss: 0.5943
Epoch 12/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7440 - loss: 0.6125 - val_accuracy: 0.7750 - val_loss: 0.5888
Epoch 13/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8028 - loss: 0.5819 - val_accuracy: 0.8250 - val_loss: 0.5834
Epoch 14/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7763 - loss: 0.6029 - val_accuracy: 0.8500 - val_loss: 0.5782
Epoch 15/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8295 - loss: 0.5960 - val_accuracy: 0.8625 - val_loss: 0.5730
Epoch 16/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8708 - loss: 0.5882 - val_accuracy: 0.8875 - val_loss: 0.5683
Epoch 17/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8882 - loss: 0.5761 - val_accuracy: 0.9000 - val_loss: 0.5634
Epoch 18/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8933 - loss: 0.5730 - val_accuracy: 0.9000 - val_loss: 0.5586
Epoch 19/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8614 - loss: 0.5824 - val_accuracy: 0.9000 - val_loss: 0.5539
Epoch 20/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8604 - loss: 0.5819 - val_accuracy: 0.9125 - val_loss: 0.5494

In [ ]:
#Try with nadam,rmsprop,adadelta,lion

# Tweak the Learning Rate Parameter

In [ ]:
#Architect the model
import tensorflow as tf

model1 = tf.keras.Sequential()

model1.add(tf.keras.layers.Dense(units = 6 , activation="relu", input_shape=(2,)))
model1.add(tf.keras.layers.Dense(units = 6 , activation="relu"))
model1.add(tf.keras.layers.Dense(units = 1 , activation="sigmoid"))

In [ ]:
#Compile Model

#For Classification
# Loss Function:
# a. Binary Classification: binary_crossentropy
# b. Multi-class Classification: categorical_crossentropy | sparse_categorical_crossentropy


model1.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
               loss="binary_crossentropy",
               metrics=["accuracy"])

In [ ]:
class MyCLRuleMonitor(tf.keras.callbacks.Callback):
  def __init__(self,cl):
    super(MyCLRuleMonitor,self).__init__()
    self.cl=cl

  def on_epoch_end(self,epoch,logs=None):
    testScore = logs.get('val_accuracy')
    trainScore = logs.get('accuracy')

    if testScore > trainScore and testScore >= self.cl:
      self.model.stop_training=True

In [ ]:
model1.fit(X_train,y_train, validation_data=(X_test,y_test), epochs=10000, callbacks=[MyCLRuleMonitor(0.9)])

Epoch 1/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step - accuracy: 0.6173 - loss: 0.6515 - val_accuracy: 0.8250 - val_loss: 0.5127
Epoch 2/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8373 - loss: 0.4651 - val_accuracy: 0.9000 - val_loss: 0.3876
Epoch 3/10000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8946 - loss: 0.3608 - val_accuracy: 0.9500 - val_loss: 0.3041

In [ ]:
#tf.keras.optimizers.Nadam(learning_rate=0.01)
#tf.keras.optimizers.RMSprop(learning_rate=0.01)
#tf.keras.optimizers.Adadelta(learning_rate=0.01)
#tf.keras.optimizers.Lion(learning_rate=0.01)

In [ ]:
#https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adadelta$0